import { NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

const AIRLINE_EMAILS: Record<string, string> = {
    "DY": "claims@norwegian.com",
    "SK": "claims@sas.no",
    "LH": "customer.relations@lufthansa.com",
    "BA": "claims@ba.com",
    "FR": "claims@ryanair.com",
    "AF": "claims@airfrance.com",
    "KL": "claims@klm.com",
    // Default
    "DEFAULT": "claims@airline.com"
};

export async function POST(req: Request) {
    const { sessionId, mockPayment, flightCode } = await req.json();

    // Determine Airline IATA
    const airlineIata = flightCode ? flightCode.substring(0, 2).toUpperCase() : "DEFAULT";
    const airlineEmail = AIRLINE_EMAILS[airlineIata] || AIRLINE_EMAILS["DEFAULT"];

    // Mock prompt if no key
    if (!process.env.GEMINI_API_KEY) {
        return NextResponse.json({
            letter: `[DEMO MODE - No Gemini Key]\n\nTO: ${airlineEmail}\n\nSUBJECT: Compensation Claim under Regulation EC 261/2004\n\nDear Sir/Madam,\n\nI am writing to claim compensation for flight ${flightCode || "FLIGHT"}... [Full legal text would appear here generated by AI].\n\nKind regards,\n[Your Name]`,
            email: airlineEmail
        });
    }

    try {
        const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
        // Use gemini-1.5-flash for speed and low cost
        const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

        const prompt = `You are a professional aviation lawyer. Write a formal legal claim letter for flight delay compensation citing Regulation EC 261/2004. 
        Airline Code: ${airlineIata}. 
        Compensation Amount: €600. 
        Keep it professional, firm, and concise. 
        Address it to the claims department. 
        Include placeholders for [Your Name], [Address], [Flight Number], [Date], and [IBAN].
        Return ONLY the letter text, no preamble.`;

        const result = await model.generateContent(prompt);
        const response = await result.response;
        const letter = response.text();

        return NextResponse.json({
            letter,
            email: airlineEmail
        });
    } catch (error) {
        console.error("Gemini Error", error);
        return NextResponse.json({
            letter: "Error generating letter. Please check your API Key or try again later.",
            email: "error"
        }, { status: 500 });
    }
}
