import { NextResponse } from "next/server";
import OpenAI from "openai";

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY || "mock-key",
});

const AIRLINE_EMAILS: Record<string, string> = {
    "DY": "claims@norwegian.com",
    "SK": "claims@sas.no",
    "LH": "customer.relations@lufthansa.com",
    "BA": "claims@ba.com",
    "FR": "claims@ryanair.com",
    "AF": "claims@airfrance.com",
    "KL": "claims@klm.com",
    // Default
    "DEFAULT": "claims@airline.com"
};

export async function POST(req: Request) {
    const { sessionId, mockPayment, flightCode } = await req.json();

    // In a real app, verify sessionId with Stripe here to ensure payment.

    // Determine Airline IATA from flightCode (e.g. DY123 -> DY)
    // flightCode might be slightly messy from URL, try to parse.
    const airlineIata = flightCode ? flightCode.substring(0, 2).toUpperCase() : "DEFAULT";
    const airlineEmail = AIRLINE_EMAILS[airlineIata] || AIRLINE_EMAILS["DEFAULT"];

    // Mock prompt if no key or for demo
    if (!process.env.OPENAI_API_KEY) {
        return NextResponse.json({
            letter: `[DEMO MODE - No OpenAI Key]\n\nTO: ${airlineEmail}\n\nSUBJECT: Compensation Claim under Regulation EC 261/2004\n\nDear Sir/Madam,\n\nI am writing to claim compensation for flight ${flightCode || "FLIGHT"}... [Full legal text would appear here generated by AI].\n\nKind regards,\n[Your Name]`,
            email: airlineEmail
        });
    }

    try {
        const completion = await openai.chat.completions.create({
            model: "gpt-4o-mini",
            messages: [
                { role: "system", content: "You are a professional aviation lawyer." },
                { role: "user", content: `Write a formal legal claim letter for flight delay compensation citing Regulation EC 261/2004. Airline: ${airlineIata}. Compensation: €600. Keep it professional, firm, and concise. Address it to the claims department. Include placeholders for [Your Name] and [IBAN].` }
            ],
            temperature: 0.7,
        });

        const letter = completion.choices[0].message.content;

        return NextResponse.json({
            letter,
            email: airlineEmail
        });
    } catch (error) {
        console.error("OpenAI Error", error);
        return NextResponse.json({
            letter: "Error generating letter. Please try again later.",
            email: "error"
        }, { status: 500 });
    }
}
