import { NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

// Enhanced Database of Airline Contacts (Emails or Form URLs)
const AIRLINE_CONTACTS: Record<string, string> = {
    // Major European
    "DY": "claims@norwegian.com", // Norwegian
    "SK": "claims@sas.no", // SAS
    "LH": "customer.relations@lufthansa.com", // Lufthansa
    "BA": "claims@ba.com", // British Airways
    "FR": "https://onlineform.ryanair.com/ie/en/contact-us-eu261", // Ryanair (Strictly form only)
    "AF": "mail.refund.service@airfrance.fr", // Air France
    "KL": "claims@klm.com", // KLM
    "EW": "service@eurowings.com", // Eurowings
    "LX": "contactus@swiss.com", // Swiss
    "OS": "customer.relations@austrian.com", // Austrian
    "IB": "clasica@iberia.es", // Iberia
    "TP": "customer.experience@tap.pt", // TAP Portugal
    "AY": "customer.relations@finnair.com", // Finnair
    "AZ": "customer.relations@ita-airways.com", // ITA
    "EI": "central.baggage.tracing@aerlingus.com", // Aer Lingus

    // Low Cost / Others
    "U2": "https://www.easyjet.com/en/claim/EU261", // EasyJet
    "W6": "https://wizzair.com/en-gb/information-and-services/compliments-and-complaints/", // Wizz Air
    "VY": "contact@vueling.com", // Vueling
    "HV": "service-center@transavia.com", // Transavia
    "LS": "customer.relations@jet2.com", // Jet2
    "BT": "info@airbaltic.com", // AirBaltic

    // US (for flights departing EU)
    "DL": "https://www.delta.com/us/en/need-help/overview", // Delta
    "UA": "https://www.united.com/en/us/customercare", // United
    "AA": "https://www.aa.com/contact/forms?topic=CR", // American

    // Default Fallback
    "DEFAULT": "claims@airline.com"
};

export async function POST(req: Request) {
    const { flightCode } = await req.json();

    // Determine Airline IATA
    const airlineIata = flightCode ? flightCode.substring(0, 2).toUpperCase() : "DEFAULT";
    const airlineContact = AIRLINE_CONTACTS[airlineIata] || AIRLINE_CONTACTS["DEFAULT"];

    // Mock prompt if no key
    if (!process.env.GEMINI_API_KEY) {
        return NextResponse.json({
            letter: `[DEMO MODE - No Gemini Key]\n\nTO: ${airlineContact}\n\nSUBJECT: Compensation Claim under Regulation EC 261/2004\n\nDear Sir/Madam,\n\nI am writing to claim compensation for flight ${flightCode || "FLIGHT"}... [Full legal text would appear here generated by AI].\n\nKind regards,\n[Your Name]`,
            email: airlineContact
        });
    }

    try {
        const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
        // Use gemini-1.5-flash for speed and low cost
        const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

        const prompt = `You are a professional aviation lawyer. Write a formal legal claim letter for flight delay compensation citing Regulation EC 261/2004. 
        Airline Code: ${airlineIata}. 
        Compensation Amount: €600. 
        Keep it professional, firm, and concise. 
        Address it to the claims department. 
        Include placeholders for [Your Name], [Address], [Flight Number], [Date], and [IBAN].
        Return ONLY the letter text, no preamble.`;

        const result = await model.generateContent(prompt);
        const response = await result.response;
        const letter = response.text();

        return NextResponse.json({
            letter,
            email: airlineContact
        });
    } catch (error) {
        console.error("Gemini Error", error);
        return NextResponse.json({
            letter: "Error generating letter. Please check your API Key or try again later.",
            email: "error"
        }, { status: 500 });
    }
}
